contact_links:
  - name: ğŸ”“ Security Reports
    url: mailto:security@forgejo.org
    about: "Please email <security@forgejo.org> (GPG: `A4676E79`) instead of opening a public issue."
  - name: ğŸ’¬ Matrix Chat Room
    url: https://matrix.to/#/#forgejo-chat:matrix.org
    about: Please ask questions and discuss configuration or deployment problems here.
  - name: ğŸ’¬ Matrix Space
    url: https://matrix.to/#/#forgejo:matrix.org
    about: A collection of Matrix rooms relating to Forgejo in addition to the main chat room.
  - name: ğŸ“š Documentation
    url: https://forgejo.org/docs/latest/
    about: Documentation about Forgejo.
  - name: â“ Frequently Asked Questions
    url: https://forgejo.org/faq/
    about: Please check if your question is mentioned here.
